#version: '3.8'
name: test-task-junior-node-danish

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danish-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - danish-network
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: danish-db
    hostname: danish-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql-danish
    networks:
      - danish-network

volumes:
  db_data:
    name: 'danish_db_data'

networks:
  danish-network:
    driver: bridge